
void retira_pontos(char *);
int verifica_letra(char *);
int valida_cnpj(char *);
int valida_cpf (char *);
void retira_pontoscpf(char *);
int verifica_letracpf(char *);
int valida_cpf(char *);
int valida_email(char *);
void cadastrado_sucesso(void);
void atualizado_sucesso(void);
void deletado_sucesso(void);
int verifica_espaco(char *);
int valida_nome(char *);
void remove_enter(char *);
void recuperado_sucesso(void);
void erro_cadastre_cerveja(void);
void cdt_mas_inativo(void);
void ja_cadastrado(void);
void dados_nalterados(void);
void fornecedor_ncadastrado(void);
void fornecedor_inativo(void);
void cadastro_nencontrado(void);
void cadastro_nocorreu(void);
void cerveja_nencontrada(void);
void cadastro_jaapagado(void);